version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "dependabot-staging"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "(Action Update):"
    reviewers:
      - "zackheil"
    assignees:
      - "zackheil"

  - package-ecosystem: "npm"
    target-branch: "dependabot-staging"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "(Dep Update):"
      prefix-development: "(Dev Dep Update):"
    reviewers:
      - "zackheil"
    assignees:
      - "zackheil"
